# Generated by Django 4.1.3 on 2022-12-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0002_juegosdecartas_juegosdemesa_videojuegos_delete_curso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nombrecarta', models.CharField(max_length=50)),
                ('rareza', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
