# Generated by Django 4.1.3 on 2022-12-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0004_rename_nombre_carta_nombrejuego_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carta',
            old_name='nombrecarta',
            new_name='Nombrecarta',
        ),
    ]
