# Generated by Django 4.1.3 on 2022-12-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0005_rename_nombrecarta_carta_nombrecarta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoJuegos',
            new_name='VideoJuegoModel',
        ),
    ]
