# Generated by Django 4.1.3 on 2022-12-01 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0006_rename_videojuegos_videojuegomodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='juegosdemesa',
        ),
    ]
