# Generated by Django 4.1.3 on 2022-12-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0007_delete_juegosdemesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='juegosdemesaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombrejuego', models.CharField(max_length=50)),
                ('Tipo_juego', models.CharField(max_length=50)),
                ('Cantidad_jugadores', models.IntegerField()),
            ],
        ),
    ]
